### ISSUE TITLE
Update mission ending conditions

### ISSUE THREAD

**Issue by MrSimbax** [MrSimbax/colobot-alludo#8]
…and use new features.

**Comment by krzys-h** [comment]
There is no longer such thing as versioning level files.
The only new feature that could be used that comes to my mind is completly removing mission ending conditions - that will result in a mission that truly never ends (in original Colobot that was an instant win)

**Comment by MrSimbax** [comment]
Done in https://github.com/MrSimbax/colobot-alludo/commit/4f4897e7765ca7b103958f82d4e564b127ead73d
